### ISSUE TITLE
"Feature may not be used on the release stable channel"

### ISSUE THREAD

**Issue by mcclure** [jmg049/wavers#8]
I have Rust 1.73.0 installed on Mac OS. I run "cargo add wavers" and "cargo run".

Cargo prints:

```
   Compiling wavers v1.0.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/mcc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wavers-1.0.1/src/lib.rs:1:12
  |
1 | #![feature(const_type_id)]
  |            ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `wavers` (lib) due to previous error
```

I do not know what that means exactly.

Expected behavior: If something is published in Cargo, it should work in stable Rust, or at minimum there should be clear warnings in the documentation / crates.io page that it requires unstable.

**Comment by jmg049** [comment]
Fair enough, I always originally did it using the ``const_type_id`` feature since it seemed like the easiest way of checking whether or not the format encoding in the wav file was the same as the desired encoding expressed through the type T which was passed to/inferred by the function.

I have a fix implemented which seems to not cause any issues. I would like to test it a small bit more tomorrow since I only implemented the fix on the current crates version of wavers. Whereas I'm currently close to releasing the next version of the crate which makes general improvements and changes to how the crate works. The functions exposed by the crate shouldn't change (if I'm remembering correctly).

**Comment by jmg049** [comment]
Ok, so apologies, I cannot get this done tonight. The fix was actually included in the updated code anyway (past me looking out for future me, I suppose). However, I do not want to publish the update without having documentation for it, and that is not something I can do tonight. 

I also prefer to keep the Python version working as well, which, unfortunately, adds time to publishing updates. Fingers crossed, tomorrow will be a better day and I will be able to get through the documentation (+ the python stuff).

**Comment by mcclure** [comment]
There is no urgency at my end as I have a workaround (saving raw floats and using Audacity "import raw data") but I appreciate you looking into it.

**Comment by jmg049** [comment]
Hey, the latest version of Wavers (1.1.0) has now been published and does not require nightly to build.
